cGateCommands = {
  name: "-n",
  comments: "-cts",
  parent_group: "-pg",
  state: "-s",
  login_user: "-lu",
  change_password_option: "-cpo",
  login_password: "-lp",
  client_password: "-cp",
  server_ident: "-si",
  client_ident: "-ci",
  tls_client_auth: "-tlscauth",
  tls_sprof: "-tlss",
  tls_sprof_user_param: "-tlssup",
  remote_public_key_alias: "-rpubka",
  remote_public_key_group: "-rpubkg",
  remote_subject_cert_alias: "-rsubcerta",
  remote_issuer_cert_alias: "-risscerta",
  remote_subject_name_pattern: "-rsubnp",
  remote_issuer_name_pattern: "-rissnp",
  ftpcs_list_fields: "-ftpcs_lf",
  root_dir: "-rd",
  home_dir: "-hd",
  user_param1: "-usp1",
  user_param2: "-usp2",
  http_home_page: "-hhp",
  http_list_template: "-hlt",
  max_download_rate: "-max_downr",
  max_download_requests_rate: "-maxdownreqr",
  max_upload_rate: "-max_upr",
  max_upload_requests_rate: "-maxupreqr",
  max_upload_file_size: "-max_upload_file_size",
  command_sensitivity: "-cmd_s",
  add_vfd_right: "-avr",
  add_calling_addr: "-acinga",
};

module.exports = { cGateCommands };
