const modelcomm = {
  dest_alias: "-da",
  model_name: "-ml",
  org_alias: "-oa",
  remote_agent: "-ra",
  protocol: "-pr",
  append: "-app",
  dirName: "-dn",
  dirNameAlias: "-dna",
  dirType: "-dt",
  localSite: "-local",
  uniqueFilename: "-uf",
  comments: "-cts",
  localAgent: "-la",
  direction: "-dir",
  type: "-ty",
  appli: "-ap",
  fileComponent: "-fc",
  sendMessage: "-sm",
  compression: "-comp",
  mode: "-m",
  priority: "-prio",
  fileOrganization: "-f_org",
  retryCountMax: "-rc_max",
  blockSize: "-bs",
  fileName: "-fn",
  purgeOption: "-po",
  ftpCommand: "-ftpc",
  rcvAppli: "-ra",
  rcvText: "-rt",
  rcvUser: "-ru",
};

module.exports = { modelcomm };
