siteCommands = {
  alias: "-a",
  proto_ident: "-pi",
  comments: "-cts",
  mail_address: "-email",
  dir_path: "-dp",
  usr_param1: "-usp1",
  usr_param2: "-usp2",
  auth_obj_type: "-auth_obj_type",
  auth_obj_name: "-auth_obj_name",
  password: "-pswd",
  protocol: "-pr",
  group: "-gr",
  username: "-un",
  partner_loc_alias: "-pla",
  init_sender: "-is",
  resp_sender: "-rs",
  init_receiver: "-ir",
  resp_receiver: "-rr",
  init_mode: "-im",
  trace_mode: "-tm",
  resp_mode: "-rm",
  data_size_max: "-ds",
  init_conn_max: "-i_max",
  init_conn_count: "-init_conn_count",
  retry_count_max: "-rc_max",
  retry_delay_min: "-rd_min",
  retry_delay_max: "-rd_max",
  sentinel_transfer_filter: "-stf",
  commpath_used: "-cu",
  comm_type: "-ct",
};

module.exports = { siteCommands };
